# HiFi-GAN V1 Model Configuration (Highest Quality)

generator:
  _target_: src.model.Generator
  in_channels: 80
  hidden_channels: 512
  upsample_rates: [8, 8, 2, 2]
  upsample_kernel_sizes: [16, 16, 4, 4]
  resblock_kernel_sizes: [3, 7, 11]
  resblock_dilations:
    - [1, 3, 5]
    - [1, 3, 5]
    - [1, 3, 5]

mpd:
  _target_: src.model.MultiPeriodDiscriminator
  periods: [2, 3, 5, 7, 11]
  use_spectral_norm: false

msd:
  _target_: src.model.MultiScaleDiscriminator
  use_spectral_norm_first: true
